// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dag.proto
// Protobuf Java Version: 4.28.3

package org.peergos.blockstore.pb;

public final class Dag {
  private Dag() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PBNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.peergos.blockstore.pb.PBNode)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    java.util.List<org.peergos.blockstore.pb.Dag.PBLink> 
        getLinksList();
    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    org.peergos.blockstore.pb.Dag.PBLink getLinks(int index);
    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    int getLinksCount();

    /**
     * <code>optional bytes Data = 1;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>optional bytes Data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code org.peergos.blockstore.pb.PBNode}
   */
  public  static final class PBNode extends
      com.google.protobuf.GeneratedMessageLite<
          PBNode, PBNode.Builder> implements
      // @@protoc_insertion_point(message_implements:org.peergos.blockstore.pb.PBNode)
      PBNodeOrBuilder {
    private PBNode() {
      links_ = emptyProtobufList();
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int LINKS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<org.peergos.blockstore.pb.Dag.PBLink> links_;
    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    @java.lang.Override
    public java.util.List<org.peergos.blockstore.pb.Dag.PBLink> getLinksList() {
      return links_;
    }
    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    public java.util.List<? extends org.peergos.blockstore.pb.Dag.PBLinkOrBuilder> 
        getLinksOrBuilderList() {
      return links_;
    }
    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    @java.lang.Override
    public int getLinksCount() {
      return links_.size();
    }
    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    @java.lang.Override
    public org.peergos.blockstore.pb.Dag.PBLink getLinks(int index) {
      return links_.get(index);
    }
    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    public org.peergos.blockstore.pb.Dag.PBLinkOrBuilder getLinksOrBuilder(
        int index) {
      return links_.get(index);
    }
    private void ensureLinksIsMutable() {
      com.google.protobuf.Internal.ProtobufList<org.peergos.blockstore.pb.Dag.PBLink> tmp = links_;
      if (!tmp.isModifiable()) {
        links_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    private void setLinks(
        int index, org.peergos.blockstore.pb.Dag.PBLink value) {
      value.getClass();
  ensureLinksIsMutable();
      links_.set(index, value);
    }
    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    private void addLinks(org.peergos.blockstore.pb.Dag.PBLink value) {
      value.getClass();
  ensureLinksIsMutable();
      links_.add(value);
    }
    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    private void addLinks(
        int index, org.peergos.blockstore.pb.Dag.PBLink value) {
      value.getClass();
  ensureLinksIsMutable();
      links_.add(index, value);
    }
    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    private void addAllLinks(
        java.lang.Iterable<? extends org.peergos.blockstore.pb.Dag.PBLink> values) {
      ensureLinksIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, links_);
    }
    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    private void clearLinks() {
      links_ = emptyProtobufList();
    }
    /**
     * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
     */
    private void removeLinks(int index) {
      ensureLinksIsMutable();
      links_.remove(index);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes Data = 1;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes Data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>optional bytes Data = 1;</code>
     * @param value The data to set.
     */
    private void setData(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      data_ = value;
    }
    /**
     * <code>optional bytes Data = 1;</code>
     */
    private void clearData() {
      bitField0_ = (bitField0_ & ~0x00000001);
      data_ = getDefaultInstance().getData();
    }

    public static org.peergos.blockstore.pb.Dag.PBNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.peergos.blockstore.pb.Dag.PBNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.peergos.blockstore.pb.Dag.PBNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.peergos.blockstore.pb.Dag.PBNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.peergos.blockstore.pb.Dag.PBNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.peergos.blockstore.pb.Dag.PBNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.peergos.blockstore.pb.Dag.PBNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.peergos.blockstore.pb.Dag.PBNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static org.peergos.blockstore.pb.Dag.PBNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static org.peergos.blockstore.pb.Dag.PBNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.peergos.blockstore.pb.Dag.PBNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.peergos.blockstore.pb.Dag.PBNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.peergos.blockstore.pb.Dag.PBNode prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code org.peergos.blockstore.pb.PBNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.peergos.blockstore.pb.Dag.PBNode, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.peergos.blockstore.pb.PBNode)
        org.peergos.blockstore.pb.Dag.PBNodeOrBuilder {
      // Construct using org.peergos.blockstore.pb.Dag.PBNode.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
       */
      @java.lang.Override
      public java.util.List<org.peergos.blockstore.pb.Dag.PBLink> getLinksList() {
        return java.util.Collections.unmodifiableList(
            instance.getLinksList());
      }
      /**
       * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
       */
      @java.lang.Override
      public int getLinksCount() {
        return instance.getLinksCount();
      }/**
       * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
       */
      @java.lang.Override
      public org.peergos.blockstore.pb.Dag.PBLink getLinks(int index) {
        return instance.getLinks(index);
      }
      /**
       * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
       */
      public Builder setLinks(
          int index, org.peergos.blockstore.pb.Dag.PBLink value) {
        copyOnWrite();
        instance.setLinks(index, value);
        return this;
      }
      /**
       * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
       */
      public Builder setLinks(
          int index, org.peergos.blockstore.pb.Dag.PBLink.Builder builderForValue) {
        copyOnWrite();
        instance.setLinks(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
       */
      public Builder addLinks(org.peergos.blockstore.pb.Dag.PBLink value) {
        copyOnWrite();
        instance.addLinks(value);
        return this;
      }
      /**
       * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
       */
      public Builder addLinks(
          int index, org.peergos.blockstore.pb.Dag.PBLink value) {
        copyOnWrite();
        instance.addLinks(index, value);
        return this;
      }
      /**
       * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
       */
      public Builder addLinks(
          org.peergos.blockstore.pb.Dag.PBLink.Builder builderForValue) {
        copyOnWrite();
        instance.addLinks(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
       */
      public Builder addLinks(
          int index, org.peergos.blockstore.pb.Dag.PBLink.Builder builderForValue) {
        copyOnWrite();
        instance.addLinks(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
       */
      public Builder addAllLinks(
          java.lang.Iterable<? extends org.peergos.blockstore.pb.Dag.PBLink> values) {
        copyOnWrite();
        instance.addAllLinks(values);
        return this;
      }
      /**
       * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
       */
      public Builder clearLinks() {
        copyOnWrite();
        instance.clearLinks();
        return this;
      }
      /**
       * <code>repeated .org.peergos.blockstore.pb.PBLink Links = 2;</code>
       */
      public Builder removeLinks(int index) {
        copyOnWrite();
        instance.removeLinks(index);
        return this;
      }

      /**
       * <code>optional bytes Data = 1;</code>
       * @return Whether the data field is set.
       */
      @java.lang.Override
      public boolean hasData() {
        return instance.hasData();
      }
      /**
       * <code>optional bytes Data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>optional bytes Data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>optional bytes Data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.peergos.blockstore.pb.PBNode)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.peergos.blockstore.pb.Dag.PBNode();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "data_",
              "links_",
              org.peergos.blockstore.pb.Dag.PBLink.class,
            };
            java.lang.String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u100a\u0000\u0002" +
                "\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.peergos.blockstore.pb.Dag.PBNode> parser = PARSER;
          if (parser == null) {
            synchronized (org.peergos.blockstore.pb.Dag.PBNode.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.peergos.blockstore.pb.Dag.PBNode>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.peergos.blockstore.pb.PBNode)
    private static final org.peergos.blockstore.pb.Dag.PBNode DEFAULT_INSTANCE;
    static {
      PBNode defaultInstance = new PBNode();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PBNode.class, defaultInstance);
    }

    public static org.peergos.blockstore.pb.Dag.PBNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PBNode> PARSER;

    public static com.google.protobuf.Parser<PBNode> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PBLinkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.peergos.blockstore.pb.PBLink)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional bytes Hash = 1;</code>
     * @return Whether the hash field is set.
     */
    boolean hasHash();
    /**
     * <code>optional bytes Hash = 1;</code>
     * @return The hash.
     */
    com.google.protobuf.ByteString getHash();

    /**
     * <code>optional string Name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string Name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string Name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional uint64 Tsize = 3;</code>
     * @return Whether the tsize field is set.
     */
    boolean hasTsize();
    /**
     * <code>optional uint64 Tsize = 3;</code>
     * @return The tsize.
     */
    long getTsize();
  }
  /**
   * Protobuf type {@code org.peergos.blockstore.pb.PBLink}
   */
  public  static final class PBLink extends
      com.google.protobuf.GeneratedMessageLite<
          PBLink, PBLink.Builder> implements
      // @@protoc_insertion_point(message_implements:org.peergos.blockstore.pb.PBLink)
      PBLinkOrBuilder {
    private PBLink() {
      hash_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
    }
    private int bitField0_;
    public static final int HASH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString hash_;
    /**
     * <code>optional bytes Hash = 1;</code>
     * @return Whether the hash field is set.
     */
    @java.lang.Override
    public boolean hasHash() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes Hash = 1;</code>
     * @return The hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }
    /**
     * <code>optional bytes Hash = 1;</code>
     * @param value The hash to set.
     */
    private void setHash(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      hash_ = value;
    }
    /**
     * <code>optional bytes Hash = 1;</code>
     */
    private void clearHash() {
      bitField0_ = (bitField0_ & ~0x00000001);
      hash_ = getDefaultInstance().getHash();
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.String name_;
    /**
     * <code>optional string Name = 2;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string Name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>optional string Name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>optional string Name = 2;</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      name_ = value;
    }
    /**
     * <code>optional string Name = 2;</code>
     */
    private void clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>optional string Name = 2;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      name_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static final int TSIZE_FIELD_NUMBER = 3;
    private long tsize_;
    /**
     * <code>optional uint64 Tsize = 3;</code>
     * @return Whether the tsize field is set.
     */
    @java.lang.Override
    public boolean hasTsize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 Tsize = 3;</code>
     * @return The tsize.
     */
    @java.lang.Override
    public long getTsize() {
      return tsize_;
    }
    /**
     * <code>optional uint64 Tsize = 3;</code>
     * @param value The tsize to set.
     */
    private void setTsize(long value) {
      bitField0_ |= 0x00000004;
      tsize_ = value;
    }
    /**
     * <code>optional uint64 Tsize = 3;</code>
     */
    private void clearTsize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tsize_ = 0L;
    }

    public static org.peergos.blockstore.pb.Dag.PBLink parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.peergos.blockstore.pb.Dag.PBLink parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.peergos.blockstore.pb.Dag.PBLink parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.peergos.blockstore.pb.Dag.PBLink parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.peergos.blockstore.pb.Dag.PBLink parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.peergos.blockstore.pb.Dag.PBLink parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.peergos.blockstore.pb.Dag.PBLink parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.peergos.blockstore.pb.Dag.PBLink parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static org.peergos.blockstore.pb.Dag.PBLink parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static org.peergos.blockstore.pb.Dag.PBLink parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.peergos.blockstore.pb.Dag.PBLink parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.peergos.blockstore.pb.Dag.PBLink parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.peergos.blockstore.pb.Dag.PBLink prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code org.peergos.blockstore.pb.PBLink}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.peergos.blockstore.pb.Dag.PBLink, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.peergos.blockstore.pb.PBLink)
        org.peergos.blockstore.pb.Dag.PBLinkOrBuilder {
      // Construct using org.peergos.blockstore.pb.Dag.PBLink.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional bytes Hash = 1;</code>
       * @return Whether the hash field is set.
       */
      @java.lang.Override
      public boolean hasHash() {
        return instance.hasHash();
      }
      /**
       * <code>optional bytes Hash = 1;</code>
       * @return The hash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getHash() {
        return instance.getHash();
      }
      /**
       * <code>optional bytes Hash = 1;</code>
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setHash(value);
        return this;
      }
      /**
       * <code>optional bytes Hash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        copyOnWrite();
        instance.clearHash();
        return this;
      }

      /**
       * <code>optional string Name = 2;</code>
       * @return Whether the name field is set.
       */
      @java.lang.Override
      public boolean hasName() {
        return instance.hasName();
      }
      /**
       * <code>optional string Name = 2;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>optional string Name = 2;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>optional string Name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>optional string Name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>optional string Name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>optional uint64 Tsize = 3;</code>
       * @return Whether the tsize field is set.
       */
      @java.lang.Override
      public boolean hasTsize() {
        return instance.hasTsize();
      }
      /**
       * <code>optional uint64 Tsize = 3;</code>
       * @return The tsize.
       */
      @java.lang.Override
      public long getTsize() {
        return instance.getTsize();
      }
      /**
       * <code>optional uint64 Tsize = 3;</code>
       * @param value The tsize to set.
       * @return This builder for chaining.
       */
      public Builder setTsize(long value) {
        copyOnWrite();
        instance.setTsize(value);
        return this;
      }
      /**
       * <code>optional uint64 Tsize = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTsize() {
        copyOnWrite();
        instance.clearTsize();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.peergos.blockstore.pb.PBLink)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.peergos.blockstore.pb.Dag.PBLink();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "hash_",
              "name_",
              "tsize_",
            };
            java.lang.String info =
                "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u100a\u0000\u0002" +
                "\u1008\u0001\u0003\u1003\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.peergos.blockstore.pb.Dag.PBLink> parser = PARSER;
          if (parser == null) {
            synchronized (org.peergos.blockstore.pb.Dag.PBLink.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.peergos.blockstore.pb.Dag.PBLink>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.peergos.blockstore.pb.PBLink)
    private static final org.peergos.blockstore.pb.Dag.PBLink DEFAULT_INSTANCE;
    static {
      PBLink defaultInstance = new PBLink();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PBLink.class, defaultInstance);
    }

    public static org.peergos.blockstore.pb.Dag.PBLink getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PBLink> PARSER;

    public static com.google.protobuf.Parser<PBLink> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
