// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: unix-fs.proto
// Protobuf Java Version: 4.28.3

package org.peergos.blockstore.pb;

public final class UnixFS {
  private UnixFS() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.peergos.blockstore.pb.Data)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .org.peergos.blockstore.pb.Data.DataType Type = 1;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>required .org.peergos.blockstore.pb.Data.DataType Type = 1;</code>
     * @return The type.
     */
    UnixFS.Data.DataType getType();

    /**
     * <code>optional bytes Data = 2;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>optional bytes Data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>optional uint64 filesize = 3;</code>
     * @return Whether the filesize field is set.
     */
    boolean hasFilesize();
    /**
     * <code>optional uint64 filesize = 3;</code>
     * @return The filesize.
     */
    long getFilesize();

    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @return A list containing the blocksizes.
     */
    java.util.List<java.lang.Long> getBlocksizesList();
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @return The count of blocksizes.
     */
    int getBlocksizesCount();
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @param index The index of the element to return.
     * @return The blocksizes at the given index.
     */
    long getBlocksizes(int index);

    /**
     * <code>optional uint64 hashType = 5;</code>
     * @return Whether the hashType field is set.
     */
    boolean hasHashType();
    /**
     * <code>optional uint64 hashType = 5;</code>
     * @return The hashType.
     */
    long getHashType();

    /**
     * <code>optional uint64 fanout = 6;</code>
     * @return Whether the fanout field is set.
     */
    boolean hasFanout();
    /**
     * <code>optional uint64 fanout = 6;</code>
     * @return The fanout.
     */
    long getFanout();

    /**
     * <code>optional uint32 mode = 7;</code>
     * @return Whether the mode field is set.
     */
    boolean hasMode();
    /**
     * <code>optional uint32 mode = 7;</code>
     * @return The mode.
     */
    int getMode();

    /**
     * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
     * @return Whether the mtime field is set.
     */
    boolean hasMtime();
    /**
     * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
     * @return The mtime.
     */
    UnixFS.UnixTime getMtime();
  }
  /**
   * Protobuf type {@code org.peergos.blockstore.pb.Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageLite<
          Data, Data.Builder> implements
      // @@protoc_insertion_point(message_implements:org.peergos.blockstore.pb.Data)
      DataOrBuilder {
    private Data() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      blocksizes_ = emptyLongList();
    }
    /**
     * Protobuf enum {@code org.peergos.blockstore.pb.Data.DataType}
     */
    public enum DataType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>Raw = 0;</code>
       */
      Raw(0),
      /**
       * <code>Directory = 1;</code>
       */
      Directory(1),
      /**
       * <code>File = 2;</code>
       */
      File(2),
      /**
       * <code>Metadata = 3;</code>
       */
      Metadata(3),
      /**
       * <code>Symlink = 4;</code>
       */
      Symlink(4),
      /**
       * <code>HAMTShard = 5;</code>
       */
      HAMTShard(5),
      ;

      /**
       * <code>Raw = 0;</code>
       */
      public static final int Raw_VALUE = 0;
      /**
       * <code>Directory = 1;</code>
       */
      public static final int Directory_VALUE = 1;
      /**
       * <code>File = 2;</code>
       */
      public static final int File_VALUE = 2;
      /**
       * <code>Metadata = 3;</code>
       */
      public static final int Metadata_VALUE = 3;
      /**
       * <code>Symlink = 4;</code>
       */
      public static final int Symlink_VALUE = 4;
      /**
       * <code>HAMTShard = 5;</code>
       */
      public static final int HAMTShard_VALUE = 5;


      @java.lang.Override
      public final int getNumber() {
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return Raw;
          case 1: return Directory;
          case 2: return File;
          case 3: return Metadata;
          case 4: return Symlink;
          case 5: return HAMTShard;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              @java.lang.Override
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return DataTypeVerifier.INSTANCE;
      }

      private static final class DataTypeVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new DataTypeVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return DataType.forNumber(number) != null;
              }
            };

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.peergos.blockstore.pb.Data.DataType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .org.peergos.blockstore.pb.Data.DataType Type = 1;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .org.peergos.blockstore.pb.Data.DataType Type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public UnixFS.Data.DataType getType() {
      UnixFS.Data.DataType result = UnixFS.Data.DataType.forNumber(type_);
      return result == null ? UnixFS.Data.DataType.Raw : result;
    }
    /**
     * <code>required .org.peergos.blockstore.pb.Data.DataType Type = 1;</code>
     * @param value The type to set.
     */
    private void setType(UnixFS.Data.DataType value) {
      type_ = value.getNumber();
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>required .org.peergos.blockstore.pb.Data.DataType Type = 1;</code>
     */
    private void clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes Data = 2;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes Data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>optional bytes Data = 2;</code>
     * @param value The data to set.
     */
    private void setData(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      data_ = value;
    }
    /**
     * <code>optional bytes Data = 2;</code>
     */
    private void clearData() {
      bitField0_ = (bitField0_ & ~0x00000002);
      data_ = getDefaultInstance().getData();
    }

    public static final int FILESIZE_FIELD_NUMBER = 3;
    private long filesize_;
    /**
     * <code>optional uint64 filesize = 3;</code>
     * @return Whether the filesize field is set.
     */
    @java.lang.Override
    public boolean hasFilesize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 filesize = 3;</code>
     * @return The filesize.
     */
    @java.lang.Override
    public long getFilesize() {
      return filesize_;
    }
    /**
     * <code>optional uint64 filesize = 3;</code>
     * @param value The filesize to set.
     */
    private void setFilesize(long value) {
      bitField0_ |= 0x00000004;
      filesize_ = value;
    }
    /**
     * <code>optional uint64 filesize = 3;</code>
     */
    private void clearFilesize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      filesize_ = 0L;
    }

    public static final int BLOCKSIZES_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.LongList blocksizes_;
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @return A list containing the blocksizes.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getBlocksizesList() {
      return blocksizes_;
    }
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @return The count of blocksizes.
     */
    @java.lang.Override
    public int getBlocksizesCount() {
      return blocksizes_.size();
    }
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @param index The index of the element to return.
     * @return The blocksizes at the given index.
     */
    @java.lang.Override
    public long getBlocksizes(int index) {
      return blocksizes_.getLong(index);
    }
    private void ensureBlocksizesIsMutable() {
      com.google.protobuf.Internal.LongList tmp = blocksizes_;
      if (!tmp.isModifiable()) {
        blocksizes_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @param index The index to set the value at.
     * @param value The blocksizes to set.
     */
    private void setBlocksizes(
        int index, long value) {
      ensureBlocksizesIsMutable();
      blocksizes_.setLong(index, value);
    }
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @param value The blocksizes to add.
     */
    private void addBlocksizes(long value) {
      ensureBlocksizesIsMutable();
      blocksizes_.addLong(value);
    }
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     * @param values The blocksizes to add.
     */
    private void addAllBlocksizes(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureBlocksizesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, blocksizes_);
    }
    /**
     * <code>repeated uint64 blocksizes = 4;</code>
     */
    private void clearBlocksizes() {
      blocksizes_ = emptyLongList();
    }

    public static final int HASHTYPE_FIELD_NUMBER = 5;
    private long hashType_;
    /**
     * <code>optional uint64 hashType = 5;</code>
     * @return Whether the hashType field is set.
     */
    @java.lang.Override
    public boolean hasHashType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint64 hashType = 5;</code>
     * @return The hashType.
     */
    @java.lang.Override
    public long getHashType() {
      return hashType_;
    }
    /**
     * <code>optional uint64 hashType = 5;</code>
     * @param value The hashType to set.
     */
    private void setHashType(long value) {
      bitField0_ |= 0x00000008;
      hashType_ = value;
    }
    /**
     * <code>optional uint64 hashType = 5;</code>
     */
    private void clearHashType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      hashType_ = 0L;
    }

    public static final int FANOUT_FIELD_NUMBER = 6;
    private long fanout_;
    /**
     * <code>optional uint64 fanout = 6;</code>
     * @return Whether the fanout field is set.
     */
    @java.lang.Override
    public boolean hasFanout() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint64 fanout = 6;</code>
     * @return The fanout.
     */
    @java.lang.Override
    public long getFanout() {
      return fanout_;
    }
    /**
     * <code>optional uint64 fanout = 6;</code>
     * @param value The fanout to set.
     */
    private void setFanout(long value) {
      bitField0_ |= 0x00000010;
      fanout_ = value;
    }
    /**
     * <code>optional uint64 fanout = 6;</code>
     */
    private void clearFanout() {
      bitField0_ = (bitField0_ & ~0x00000010);
      fanout_ = 0L;
    }

    public static final int MODE_FIELD_NUMBER = 7;
    private int mode_;
    /**
     * <code>optional uint32 mode = 7;</code>
     * @return Whether the mode field is set.
     */
    @java.lang.Override
    public boolean hasMode() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint32 mode = 7;</code>
     * @return The mode.
     */
    @java.lang.Override
    public int getMode() {
      return mode_;
    }
    /**
     * <code>optional uint32 mode = 7;</code>
     * @param value The mode to set.
     */
    private void setMode(int value) {
      bitField0_ |= 0x00000020;
      mode_ = value;
    }
    /**
     * <code>optional uint32 mode = 7;</code>
     */
    private void clearMode() {
      bitField0_ = (bitField0_ & ~0x00000020);
      mode_ = 0;
    }

    public static final int MTIME_FIELD_NUMBER = 8;
    private UnixFS.UnixTime mtime_;
    /**
     * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
     */
    @java.lang.Override
    public boolean hasMtime() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
     */
    @java.lang.Override
    public UnixFS.UnixTime getMtime() {
      return mtime_ == null ? UnixFS.UnixTime.getDefaultInstance() : mtime_;
    }
    /**
     * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
     */
    private void setMtime(UnixFS.UnixTime value) {
      value.getClass();
  mtime_ = value;
      bitField0_ |= 0x00000040;
      }
    /**
     * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeMtime(UnixFS.UnixTime value) {
      value.getClass();
  if (mtime_ != null &&
          mtime_ != UnixFS.UnixTime.getDefaultInstance()) {
        mtime_ =
          UnixFS.UnixTime.newBuilder(mtime_).mergeFrom(value).buildPartial();
      } else {
        mtime_ = value;
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
     */
    private void clearMtime() {  mtime_ = null;
      bitField0_ = (bitField0_ & ~0x00000040);
    }

    public static UnixFS.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UnixFS.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UnixFS.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UnixFS.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UnixFS.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UnixFS.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UnixFS.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UnixFS.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static UnixFS.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static UnixFS.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UnixFS.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UnixFS.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(UnixFS.Data prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code org.peergos.blockstore.pb.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          UnixFS.Data, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.peergos.blockstore.pb.Data)
        UnixFS.DataOrBuilder {
      // Construct using org.peergos.blockstore.pb.UnixFs.Data.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .org.peergos.blockstore.pb.Data.DataType Type = 1;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override
      public boolean hasType() {
        return instance.hasType();
      }
      /**
       * <code>required .org.peergos.blockstore.pb.Data.DataType Type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public UnixFS.Data.DataType getType() {
        return instance.getType();
      }
      /**
       * <code>required .org.peergos.blockstore.pb.Data.DataType Type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setType(UnixFS.Data.DataType value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>required .org.peergos.blockstore.pb.Data.DataType Type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <code>optional bytes Data = 2;</code>
       * @return Whether the data field is set.
       */
      @java.lang.Override
      public boolean hasData() {
        return instance.hasData();
      }
      /**
       * <code>optional bytes Data = 2;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>optional bytes Data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>optional bytes Data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      /**
       * <code>optional uint64 filesize = 3;</code>
       * @return Whether the filesize field is set.
       */
      @java.lang.Override
      public boolean hasFilesize() {
        return instance.hasFilesize();
      }
      /**
       * <code>optional uint64 filesize = 3;</code>
       * @return The filesize.
       */
      @java.lang.Override
      public long getFilesize() {
        return instance.getFilesize();
      }
      /**
       * <code>optional uint64 filesize = 3;</code>
       * @param value The filesize to set.
       * @return This builder for chaining.
       */
      public Builder setFilesize(long value) {
        copyOnWrite();
        instance.setFilesize(value);
        return this;
      }
      /**
       * <code>optional uint64 filesize = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilesize() {
        copyOnWrite();
        instance.clearFilesize();
        return this;
      }

      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @return A list containing the blocksizes.
       */
      @java.lang.Override
      public java.util.List<java.lang.Long>
          getBlocksizesList() {
        return java.util.Collections.unmodifiableList(
            instance.getBlocksizesList());
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @return The count of blocksizes.
       */
      @java.lang.Override
      public int getBlocksizesCount() {
        return instance.getBlocksizesCount();
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @param index The index of the element to return.
       * @return The blocksizes at the given index.
       */
      @java.lang.Override
      public long getBlocksizes(int index) {
        return instance.getBlocksizes(index);
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @param value The blocksizes to set.
       * @return This builder for chaining.
       */
      public Builder setBlocksizes(
          int index, long value) {
        copyOnWrite();
        instance.setBlocksizes(index, value);
        return this;
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @param value The blocksizes to add.
       * @return This builder for chaining.
       */
      public Builder addBlocksizes(long value) {
        copyOnWrite();
        instance.addBlocksizes(value);
        return this;
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @param values The blocksizes to add.
       * @return This builder for chaining.
       */
      public Builder addAllBlocksizes(
          java.lang.Iterable<? extends java.lang.Long> values) {
        copyOnWrite();
        instance.addAllBlocksizes(values);
        return this;
      }
      /**
       * <code>repeated uint64 blocksizes = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlocksizes() {
        copyOnWrite();
        instance.clearBlocksizes();
        return this;
      }

      /**
       * <code>optional uint64 hashType = 5;</code>
       * @return Whether the hashType field is set.
       */
      @java.lang.Override
      public boolean hasHashType() {
        return instance.hasHashType();
      }
      /**
       * <code>optional uint64 hashType = 5;</code>
       * @return The hashType.
       */
      @java.lang.Override
      public long getHashType() {
        return instance.getHashType();
      }
      /**
       * <code>optional uint64 hashType = 5;</code>
       * @param value The hashType to set.
       * @return This builder for chaining.
       */
      public Builder setHashType(long value) {
        copyOnWrite();
        instance.setHashType(value);
        return this;
      }
      /**
       * <code>optional uint64 hashType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHashType() {
        copyOnWrite();
        instance.clearHashType();
        return this;
      }

      /**
       * <code>optional uint64 fanout = 6;</code>
       * @return Whether the fanout field is set.
       */
      @java.lang.Override
      public boolean hasFanout() {
        return instance.hasFanout();
      }
      /**
       * <code>optional uint64 fanout = 6;</code>
       * @return The fanout.
       */
      @java.lang.Override
      public long getFanout() {
        return instance.getFanout();
      }
      /**
       * <code>optional uint64 fanout = 6;</code>
       * @param value The fanout to set.
       * @return This builder for chaining.
       */
      public Builder setFanout(long value) {
        copyOnWrite();
        instance.setFanout(value);
        return this;
      }
      /**
       * <code>optional uint64 fanout = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFanout() {
        copyOnWrite();
        instance.clearFanout();
        return this;
      }

      /**
       * <code>optional uint32 mode = 7;</code>
       * @return Whether the mode field is set.
       */
      @java.lang.Override
      public boolean hasMode() {
        return instance.hasMode();
      }
      /**
       * <code>optional uint32 mode = 7;</code>
       * @return The mode.
       */
      @java.lang.Override
      public int getMode() {
        return instance.getMode();
      }
      /**
       * <code>optional uint32 mode = 7;</code>
       * @param value The mode to set.
       * @return This builder for chaining.
       */
      public Builder setMode(int value) {
        copyOnWrite();
        instance.setMode(value);
        return this;
      }
      /**
       * <code>optional uint32 mode = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMode() {
        copyOnWrite();
        instance.clearMode();
        return this;
      }

      /**
       * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
       */
      @java.lang.Override
      public boolean hasMtime() {
        return instance.hasMtime();
      }
      /**
       * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
       */
      @java.lang.Override
      public UnixFS.UnixTime getMtime() {
        return instance.getMtime();
      }
      /**
       * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
       */
      public Builder setMtime(UnixFS.UnixTime value) {
        copyOnWrite();
        instance.setMtime(value);
        return this;
        }
      /**
       * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
       */
      public Builder setMtime(
          UnixFS.UnixTime.Builder builderForValue) {
        copyOnWrite();
        instance.setMtime(builderForValue.build());
        return this;
      }
      /**
       * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
       */
      public Builder mergeMtime(UnixFS.UnixTime value) {
        copyOnWrite();
        instance.mergeMtime(value);
        return this;
      }
      /**
       * <code>optional .org.peergos.blockstore.pb.UnixTime mtime = 8;</code>
       */
      public Builder clearMtime() {  copyOnWrite();
        instance.clearMtime();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.peergos.blockstore.pb.Data)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new UnixFS.Data();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "type_",
              UnixFS.Data.DataType.internalGetVerifier(),
              "data_",
              "filesize_",
              "blocksizes_",
              "hashType_",
              "fanout_",
              "mode_",
              "mtime_",
            };
            java.lang.String info =
                "\u0001\b\u0000\u0001\u0001\b\b\u0000\u0001\u0002\u0001\u1d0c\u0000\u0002\u100a\u0001" +
                "\u0003\u1003\u0002\u0004\u0015\u0005\u1003\u0003\u0006\u1003\u0004\u0007\u100b\u0005" +
                "\b\u1409\u0006";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<UnixFS.Data> parser = PARSER;
          if (parser == null) {
            synchronized (UnixFS.Data.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<UnixFS.Data>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.peergos.blockstore.pb.Data)
    private static final UnixFS.Data DEFAULT_INSTANCE;
    static {
      Data defaultInstance = new Data();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Data.class, defaultInstance);
    }

    public static UnixFS.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Data> PARSER;

    public static com.google.protobuf.Parser<Data> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.peergos.blockstore.pb.Metadata)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string MimeType = 1;</code>
     * @return Whether the mimeType field is set.
     */
    boolean hasMimeType();
    /**
     * <code>optional string MimeType = 1;</code>
     * @return The mimeType.
     */
    java.lang.String getMimeType();
    /**
     * <code>optional string MimeType = 1;</code>
     * @return The bytes for mimeType.
     */
    com.google.protobuf.ByteString
        getMimeTypeBytes();
  }
  /**
   * Protobuf type {@code org.peergos.blockstore.pb.Metadata}
   */
  public  static final class Metadata extends
      com.google.protobuf.GeneratedMessageLite<
          Metadata, Metadata.Builder> implements
      // @@protoc_insertion_point(message_implements:org.peergos.blockstore.pb.Metadata)
      MetadataOrBuilder {
    private Metadata() {
      mimeType_ = "";
    }
    private int bitField0_;
    public static final int MIMETYPE_FIELD_NUMBER = 1;
    private java.lang.String mimeType_;
    /**
     * <code>optional string MimeType = 1;</code>
     * @return Whether the mimeType field is set.
     */
    @java.lang.Override
    public boolean hasMimeType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string MimeType = 1;</code>
     * @return The mimeType.
     */
    @java.lang.Override
    public java.lang.String getMimeType() {
      return mimeType_;
    }
    /**
     * <code>optional string MimeType = 1;</code>
     * @return The bytes for mimeType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mimeType_);
    }
    /**
     * <code>optional string MimeType = 1;</code>
     * @param value The mimeType to set.
     */
    private void setMimeType(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      mimeType_ = value;
    }
    /**
     * <code>optional string MimeType = 1;</code>
     */
    private void clearMimeType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      mimeType_ = getDefaultInstance().getMimeType();
    }
    /**
     * <code>optional string MimeType = 1;</code>
     * @param value The bytes for mimeType to set.
     */
    private void setMimeTypeBytes(
        com.google.protobuf.ByteString value) {
      mimeType_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static UnixFS.Metadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UnixFS.Metadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UnixFS.Metadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UnixFS.Metadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UnixFS.Metadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UnixFS.Metadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UnixFS.Metadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UnixFS.Metadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static UnixFS.Metadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static UnixFS.Metadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UnixFS.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UnixFS.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(UnixFS.Metadata prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code org.peergos.blockstore.pb.Metadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          UnixFS.Metadata, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.peergos.blockstore.pb.Metadata)
        UnixFS.MetadataOrBuilder {
      // Construct using org.peergos.blockstore.pb.UnixFs.Metadata.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string MimeType = 1;</code>
       * @return Whether the mimeType field is set.
       */
      @java.lang.Override
      public boolean hasMimeType() {
        return instance.hasMimeType();
      }
      /**
       * <code>optional string MimeType = 1;</code>
       * @return The mimeType.
       */
      @java.lang.Override
      public java.lang.String getMimeType() {
        return instance.getMimeType();
      }
      /**
       * <code>optional string MimeType = 1;</code>
       * @return The bytes for mimeType.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMimeTypeBytes() {
        return instance.getMimeTypeBytes();
      }
      /**
       * <code>optional string MimeType = 1;</code>
       * @param value The mimeType to set.
       * @return This builder for chaining.
       */
      public Builder setMimeType(
          java.lang.String value) {
        copyOnWrite();
        instance.setMimeType(value);
        return this;
      }
      /**
       * <code>optional string MimeType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMimeType() {
        copyOnWrite();
        instance.clearMimeType();
        return this;
      }
      /**
       * <code>optional string MimeType = 1;</code>
       * @param value The bytes for mimeType to set.
       * @return This builder for chaining.
       */
      public Builder setMimeTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMimeTypeBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.peergos.blockstore.pb.Metadata)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new UnixFS.Metadata();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "mimeType_",
            };
            java.lang.String info =
                "\u0001\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1008\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<UnixFS.Metadata> parser = PARSER;
          if (parser == null) {
            synchronized (UnixFS.Metadata.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<UnixFS.Metadata>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.peergos.blockstore.pb.Metadata)
    private static final UnixFS.Metadata DEFAULT_INSTANCE;
    static {
      Metadata defaultInstance = new Metadata();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Metadata.class, defaultInstance);
    }

    public static UnixFS.Metadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Metadata> PARSER;

    public static com.google.protobuf.Parser<Metadata> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UnixTimeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.peergos.blockstore.pb.UnixTime)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int64 Seconds = 1;</code>
     * @return Whether the seconds field is set.
     */
    boolean hasSeconds();
    /**
     * <code>required int64 Seconds = 1;</code>
     * @return The seconds.
     */
    long getSeconds();

    /**
     * <code>optional fixed32 FractionalNanoseconds = 2;</code>
     * @return Whether the fractionalNanoseconds field is set.
     */
    boolean hasFractionalNanoseconds();
    /**
     * <code>optional fixed32 FractionalNanoseconds = 2;</code>
     * @return The fractionalNanoseconds.
     */
    int getFractionalNanoseconds();
  }
  /**
   * Protobuf type {@code org.peergos.blockstore.pb.UnixTime}
   */
  public  static final class UnixTime extends
      com.google.protobuf.GeneratedMessageLite<
          UnixTime, UnixTime.Builder> implements
      // @@protoc_insertion_point(message_implements:org.peergos.blockstore.pb.UnixTime)
      UnixTimeOrBuilder {
    private UnixTime() {
    }
    private int bitField0_;
    public static final int SECONDS_FIELD_NUMBER = 1;
    private long seconds_;
    /**
     * <code>required int64 Seconds = 1;</code>
     * @return Whether the seconds field is set.
     */
    @java.lang.Override
    public boolean hasSeconds() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 Seconds = 1;</code>
     * @return The seconds.
     */
    @java.lang.Override
    public long getSeconds() {
      return seconds_;
    }
    /**
     * <code>required int64 Seconds = 1;</code>
     * @param value The seconds to set.
     */
    private void setSeconds(long value) {
      bitField0_ |= 0x00000001;
      seconds_ = value;
    }
    /**
     * <code>required int64 Seconds = 1;</code>
     */
    private void clearSeconds() {
      bitField0_ = (bitField0_ & ~0x00000001);
      seconds_ = 0L;
    }

    public static final int FRACTIONALNANOSECONDS_FIELD_NUMBER = 2;
    private int fractionalNanoseconds_;
    /**
     * <code>optional fixed32 FractionalNanoseconds = 2;</code>
     * @return Whether the fractionalNanoseconds field is set.
     */
    @java.lang.Override
    public boolean hasFractionalNanoseconds() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional fixed32 FractionalNanoseconds = 2;</code>
     * @return The fractionalNanoseconds.
     */
    @java.lang.Override
    public int getFractionalNanoseconds() {
      return fractionalNanoseconds_;
    }
    /**
     * <code>optional fixed32 FractionalNanoseconds = 2;</code>
     * @param value The fractionalNanoseconds to set.
     */
    private void setFractionalNanoseconds(int value) {
      bitField0_ |= 0x00000002;
      fractionalNanoseconds_ = value;
    }
    /**
     * <code>optional fixed32 FractionalNanoseconds = 2;</code>
     */
    private void clearFractionalNanoseconds() {
      bitField0_ = (bitField0_ & ~0x00000002);
      fractionalNanoseconds_ = 0;
    }

    public static UnixFS.UnixTime parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UnixFS.UnixTime parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UnixFS.UnixTime parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UnixFS.UnixTime parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UnixFS.UnixTime parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UnixFS.UnixTime parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UnixFS.UnixTime parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UnixFS.UnixTime parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static UnixFS.UnixTime parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static UnixFS.UnixTime parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UnixFS.UnixTime parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UnixFS.UnixTime parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(UnixFS.UnixTime prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code org.peergos.blockstore.pb.UnixTime}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          UnixFS.UnixTime, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.peergos.blockstore.pb.UnixTime)
        UnixFS.UnixTimeOrBuilder {
      // Construct using org.peergos.blockstore.pb.UnixFs.UnixTime.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int64 Seconds = 1;</code>
       * @return Whether the seconds field is set.
       */
      @java.lang.Override
      public boolean hasSeconds() {
        return instance.hasSeconds();
      }
      /**
       * <code>required int64 Seconds = 1;</code>
       * @return The seconds.
       */
      @java.lang.Override
      public long getSeconds() {
        return instance.getSeconds();
      }
      /**
       * <code>required int64 Seconds = 1;</code>
       * @param value The seconds to set.
       * @return This builder for chaining.
       */
      public Builder setSeconds(long value) {
        copyOnWrite();
        instance.setSeconds(value);
        return this;
      }
      /**
       * <code>required int64 Seconds = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeconds() {
        copyOnWrite();
        instance.clearSeconds();
        return this;
      }

      /**
       * <code>optional fixed32 FractionalNanoseconds = 2;</code>
       * @return Whether the fractionalNanoseconds field is set.
       */
      @java.lang.Override
      public boolean hasFractionalNanoseconds() {
        return instance.hasFractionalNanoseconds();
      }
      /**
       * <code>optional fixed32 FractionalNanoseconds = 2;</code>
       * @return The fractionalNanoseconds.
       */
      @java.lang.Override
      public int getFractionalNanoseconds() {
        return instance.getFractionalNanoseconds();
      }
      /**
       * <code>optional fixed32 FractionalNanoseconds = 2;</code>
       * @param value The fractionalNanoseconds to set.
       * @return This builder for chaining.
       */
      public Builder setFractionalNanoseconds(int value) {
        copyOnWrite();
        instance.setFractionalNanoseconds(value);
        return this;
      }
      /**
       * <code>optional fixed32 FractionalNanoseconds = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFractionalNanoseconds() {
        copyOnWrite();
        instance.clearFractionalNanoseconds();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.peergos.blockstore.pb.UnixTime)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new UnixFS.UnixTime();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "seconds_",
              "fractionalNanoseconds_",
            };
            java.lang.String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0001\u0001\u1502\u0000\u0002" +
                "\u1006\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<UnixFS.UnixTime> parser = PARSER;
          if (parser == null) {
            synchronized (UnixFS.UnixTime.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<UnixFS.UnixTime>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.peergos.blockstore.pb.UnixTime)
    private static final UnixFS.UnixTime DEFAULT_INSTANCE;
    static {
      UnixTime defaultInstance = new UnixTime();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        UnixTime.class, defaultInstance);
    }

    public static UnixFS.UnixTime getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UnixTime> PARSER;

    public static com.google.protobuf.Parser<UnixTime> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
